### ISSUE TITLE
您好，非常精彩的论文，迁移效果真的很不错，但是我使用的SSIM评估代码可能有问题，您能分享此项目所使用的SSIM评估代码吗？非常感谢您

### ISSUE THREAD

**Issue by Rorschach-xyz** [EndyWon/MicroAST#3]
from skimage.metrics import structural_similarity as ssim
def SSIM(stylized,content):
    ssim_=ssim(stylized,content, multichannel=True)
    #ssim_=ssim(stylized,content , win_size=11, multichannel=True,sigma=1.5, data_range=1, use_sample_covariance=False, gaussian_weights=True)
    return ssim_

**Comment by EndyWon** [comment]
感谢对该工作的关注，我会尽快将SSIM的评估代码上传github

**Comment by Rorschach-xyz** [comment]
> 感谢对该工作的关注，我会尽快将SSIM的评估代码上传github

麻烦您了，非常感谢

**Comment by EndyWon** [comment]
SSIM的评估代码已上传。
