### ISSUE TITLE
Cuda out of memory about calc_cs_loss.py

### ISSUE THREAD

**Issue by Meimeiainaonao** [EndyWon/MicroAST#4]
Thanks for your sharing your code. It's wonderful work I think~~

I have one question about the  calc_cs_loss.py. when I would like to calculate the StyleLoss or ContenLoss by using the calc_cs_loss.py, the code mentioned that cuda out of memory.  My device is an NVIDIA RTX 3090 GPU (24G). May I know how can I calculate the style loss and content loss? In your paper, you just use one NVIDIA RTX 2080 GPU.

Thx for your sharing again!
![屏幕截图 2023-03-31 182253](https://user-images.githubusercontent.com/23731962/229094906-10a2fddb-c608-4aa8-8f5b-fbb6c7c3dd68.png)

**Comment by EndyWon** [comment]
The issue has been addressed by the new code, please check it.
