### ISSUE TITLE
需要您的帮助，内容和损失网络评估代码需要修改哪里能近似论文里面的数据，我在好几个模型上测试了，数据和论文里差很多

### ISSUE THREAD

**Issue by Rorschach-xyz** [EndyWon/MicroAST#5]
![image](https://user-images.githubusercontent.com/43670613/231447052-d6012d40-00ad-41e7-8835-79fca77e996d.png)
![image](https://user-images.githubusercontent.com/43670613/231447879-b50bd3f8-9321-4ddf-a2f1-3187444fe642.png)
MicroAST和StyTR2

**Comment by EndyWon** [comment]
我们在计算风格损失时因为内存的原因所以将风格图像和输出图像统一缩小到了256x256像素来计算风格损失。
