### ISSUE TITLE
Transfers color but not style

### ISSUE THREAD

**Issue by keithlostracco** [EndyWon/MicroAST#7]
Hi, thank you for sharing your work. 

I currently have it running video with a 1920x1080 content input (>30 fps), but I'm not really seeing a style transfer with the weights posted here. I definitely see color transfer, but it's not really picking up spatial style details. 

I've also ran it just with your script for testing images, and I don't really see the style transfer there as well. Just color replacement, blurring, and some artifacts. 

Am I missing something? Do I need to train before testing? If I do have to train, can you give me an idea of how long it would take with N GPUs? 

Thanks,
Keith

**Comment by EndyWon** [comment]
Sorry for the late reply. The stylization degree can be enhanced by using a larger style weight in training. The training just takes around one day on a single GPU card (e.g., 2080Ti).
